### ISSUE TITLE
https://get.helm.sh/helm-v3.2.3-darwin-arm64.tar.gz link has disappeared

### ISSUE THREAD

**Issue by calder-holt** [Antiarchitect/asdf-helm#11]
The asdf plugin breaks on install because the URL is no longer valid.

https://get.helm.sh/helm-v3.2.3-darwin-arm64.tar.gz

**Comment by Antiarchitect** [comment]
Seems like you're trying to install a very old Helm. Those versions were released before the M1 processor ever existed and darwin-arm64 target did not either.
